name: Swift Package Manager Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macos-15
    
    steps:
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_16.1.app/Contents/Developer'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and test
      run: swift test
